### ISSUE TITLE
Softlock in Phazon mines

### ISSUE THREAD

**Issue by KnilKrad** [etaylor8086/metroid-prime-randomizer#10]
Version: 1.0.0-beta.9
Permalink: Mzk5MjU3MTA3NDMxNDI0MCw5VjlCUUFBQUFBQUozQg==
Seed: 3992571074314240
Logic: Default
Mode: All Bosses
Artifacts: N/A

Description of problem: Stuck in Quarry Access room - accessible without wave beam, but cannot be escaped without it. 

Spoiler log (if available):
{
	"info": {
		"version": "1.0.0-beta.9",
		"permalink": "Mzk5MjU3MTA3NDMxNDI0MCw5VjlCUUFBQUFBQUozQg==",
		"seed": 3992571074314240,
		"settings": {
			"barsSkip": false,
			"bypassBombsWithBoost": false,
			"damageBoostLiquids": false,
			"dashing": false,
			"dbj": false,
			"dontRequireFlaahgra": false,
			"dontRequireOmegaPirate": false,
			"dontRequireThardus": false,
			"earlyMagmoorNoSuit": false,
			"earlyMagmoorNoSuitTanks": 7,
			"earlyNewborn": false,
			"earlyWild": false,
			"floatyJump": false,
			"ghettoJumping": false,
			"goal": "all-bosses",
			"goalArtifacts": 12,
			"halfPipeBombJumps": false,
			"hbjPastHote": false,
			"hideItemIcons": true,
			"ibbf": false,
			"infiniteBoostEliteResearch": false,
			"infiniteSpeedEarlySun": false,
			"infiniteSpeedHote": false,
			"infiniteSpeedMagmaPool": false,
			"lJumping": false,
			"noBombsPointOfNoReturnTunnels": false,
			"noBoostBallLowerMinesGlitched": false,
			"noCrashedFrigate": false,
			"noEarlyPhazonSuit": false,
			"noGravitySuitInGravityChamber": false,
			"noReversePhendranaBombs": true,
			"noSupers": false,
			"noVanillaBeams": false,
			"oobNoBombs": false,
			"phazonMiningTunnelNoPhazonSuit": false,
			"rJumping": false,
			"requireThermal": true,
			"requireXRay": true,
			"rootCaveSW": false,
			"shuffleArtifacts": true,
			"shuffleBombs": true,
			"shuffleCharge": true,
			"shuffleMissileLauncher": true,
			"shuffleMorph": true,
			"shuffleSpaceJump": true,
			"skipFrigate": true,
			"skipHudPopups": true,
			"spiderlessShafts": false,
			"spinnersNoBoost": false,
			"spoiler": true,
			"standableTerrain": false,
			"trainingChamberOOB": false,
			"vmr": false,
			"vmrTanks": 5,
			"waveSun": false,
			"workstationToPlasmaProcessing": false
		}
	},
	"locations": {
		"Tallon Overworld": {
			"Landing Site": "Missile Launcher",
			"Alcove": "Ice Spreader",
			"Frigate Crash Site": "Boost Ball",
			"Overgrown Cavern": "Flamethrower",
			"Root Cave": "Missile Expansion",
			"Artifact Temple": "Missile Expansion",
			"Transport Tunnel B": "Missile Expansion",
			"Arbor Chamber": "Power Bomb Expansion",
			"Cargo Freight Lift to Deck Gamma": "Missile Expansion",
			"Biohazard Containment": "Missile Expansion",
			"Hydro Access Tunnel": "Missile Expansion",
			"Great Tree Chamber": "Missile Expansion",
			"Life Grove Tunnel": "Power Bomb Expansion",
			"Life Grove (Start)": "Missile Expansion",
			"Life Grove (Underwater Spinner)": "Missile Expansion"
		},
		"Chozo Ruins": {
			"Main Plaza (Half-Pipe)": "Energy Tank",
			"Main Plaza (Grapple Ledge)": "Energy Tank",
			"Main Plaza (Tree)": "Missile Expansion",
			"Main Plaza (Locked Door)": "Morph Ball Bomb",
			"Ruined Fountain": "Missile Expansion",
			"Ruined Shrine (Beetle Battle)": "Missile Expansion",
			"Ruined Shrine (Half-Pipe)": "Missile Expansion",
			"Ruined Shrine (Lower Tunnel)": "Missile Expansion",
			"Vault": "Missile Expansion",
			"Training Chamber": "Missile Expansion",
			"Ruined Nursery": "Thermal Visor",
			"Training Chamber Access": "Phazon Suit",
			"Magma Pool": "Super Missile",
			"Tower of Light": "Power Bomb Expansion",
			"Tower Chamber": "Energy Tank",
			"Ruined Gallery (Missile Wall)": "Missile Expansion",
			"Ruined Gallery (Tunnel)": "Missile Expansion",
			"Transport Access North": "Missile Expansion",
			"Gathering Hall": "Spider Ball",
			"Hive Totem": "Morph Ball",
			"Sunchamber (Flaahgra)": "Artifact of World",
			"Sunchamber (Ghosts)": "Missile Expansion",
			"Watery Hall Access": "Gravity Suit",
			"Watery Hall (Scan Puzzle)": "Energy Tank",
			"Watery Hall (Underwater)": "Missile Expansion",
			"Dynamo (Lower)": "Missile Expansion",
			"Dynamo (Spider Track)": "Missile Expansion",
			"Burn Dome (Tunnel)": "Missile Expansion",
			"Burn Dome (I. Drone)": "Missile Expansion",
			"Furnace (Spider Tracks)": "Missile Expansion",
			"Furnace (Tunnel)": "Missile Expansion",
			"Hall of the Elders": "Missile Expansion",
			"Crossway": "Energy Tank",
			"Elder Chamber": "Missile Expansion",
			"Antechamber": "Missile Expansion"
		},
		"Magmoor Caverns": {
			"Lava Lake": "Missile Expansion",
			"Triclops Pit": "Missile Expansion",
			"Storage Cavern": "Space Jump Boots",
			"Transport Tunnel A": "Missile Expansion",
			"Warrior Shrine": "Missile Expansion",
			"Shore Tunnel": "Energy Tank",
			"Fiery Shores (Morph Track)": "Ice Beam",
			"Fiery Shores (Warrior Shrine Tunnel)": "Energy Tank",
			"Plasma Processing": "Missile Expansion",
			"Magmoor Workstation": "Energy Tank"
		},
		"Phendrana Drifts": {
			"Phendrana Shorelines (Behind Ice)": "Missile Expansion",
			"Phendrana Shorelines (Spider Track)": "Energy Tank",
			"Chozo Ice Temple": "Missile Expansion",
			"Ice Ruins West": "Missile Expansion",
			"Ice Ruins East (Behind Ice)": "Energy Tank",
			"Ice Ruins East (Spider Track)": "Charge Beam",
			"Chapel of the Elders": "Energy Tank",
			"Ruined Courtyard": "Energy Tank",
			"Phendrana Canyon": "Wave Beam",
			"Quarantine Cave": "Artifact of Truth",
			"Research Lab Hydra": "Missile Expansion",
			"Quarantine Monitor": "Power Bomb Expansion",
			"Observatory": "Missile Expansion",
			"Transport Access": "Missile Expansion",
			"Control Tower": "Missile Expansion",
			"Research Core": "Missile Expansion",
			"Frost Cave": "Varia Suit",
			"Research Lab Aether (Tank)": "Missile Expansion",
			"Research Lab Aether (Morph Track)": "Missile Expansion",
			"Gravity Chamber (Underwater)": "Missile Expansion",
			"Gravity Chamber (Grapple Ledge)": "Missile Expansion",
			"Storage Cave": "Missile Expansion",
			"Security Cave": "Missile Expansion"
		},
		"Phazon Mines": {
			"Main Quarry": "X-Ray Visor",
			"Security Access A": "Missile Expansion",
			"Storage Depot B": "Energy Tank",
			"Storage Depot A": "Wavebuster",
			"Elite Research (Phazon Elite)": "Grapple Beam",
			"Elite Research (Laser)": "Missile Expansion",
			"Elite Control Access": "Plasma Beam",
			"Ventilation Shaft": "Missile Expansion",
			"Phazon Processing Center": "Missile Expansion",
			"Processing Center Access": "Power Bomb",
			"Elite Quarters": "Artifact of Nature",
			"Central Dynamo": "Missile Expansion",
			"Metroid Quarantine B": "Energy Tank",
			"Metroid Quarantine A": "Missile Expansion",
			"Fungal Hall B": "Missile Expansion",
			"Phazon Mining Tunnel": "Missile Expansion",
			"Fungal Hall Access": "Missile Expansion"
		}
	},
	"walkthrough": [
		{
			"Hive Totem": "Morph Ball"
		},
		{
			"Landing Site": "Missile Launcher"
		},
		{
			"Artifact Temple": "Missile Expansion",
			"Transport Tunnel B": "Missile Expansion",
			"Main Plaza (Locked Door)": "Morph Ball Bomb",
			"Ruined Shrine (Beetle Battle)": "Missile Expansion",
			"Ruined Gallery (Missile Wall)": "Missile Expansion",
			"Transport Access North": "Missile Expansion",
			"Watery Hall Access": "Gravity Suit",
			"Watery Hall (Scan Puzzle)": "Energy Tank"
		},
		{
			"Ruined Shrine (Lower Tunnel)": "Missile Expansion",
			"Vault": "Missile Expansion",
			"Ruined Nursery": "Thermal Visor",
			"Ruined Gallery (Tunnel)": "Missile Expansion",
			"Sunchamber (Flaahgra)": "Artifact of World",
			"Dynamo (Lower)": "Missile Expansion",
			"Burn Dome (Tunnel)": "Missile Expansion",
			"Burn Dome (I. Drone)": "Missile Expansion",
			"Furnace (Tunnel)": "Missile Expansion",
			"Storage Cavern": "Space Jump Boots",
			"Transport Tunnel A": "Missile Expansion",
			"Fiery Shores (Morph Track)": "Ice Beam"
		},
		{
			"Alcove": "Ice Spreader",
			"Frigate Crash Site": "Boost Ball",
			"Gathering Hall": "Spider Ball",
			"Watery Hall (Underwater)": "Missile Expansion",
			"Lava Lake": "Missile Expansion",
			"Phendrana Canyon": "Wave Beam"
		},
		{
			"Overgrown Cavern": "Flamethrower",
			"Cargo Freight Lift to Deck Gamma": "Missile Expansion",
			"Hydro Access Tunnel": "Missile Expansion",
			"Main Plaza (Half-Pipe)": "Energy Tank",
			"Ruined Fountain": "Missile Expansion",
			"Ruined Shrine (Half-Pipe)": "Missile Expansion",
			"Tower of Light": "Power Bomb Expansion",
			"Tower Chamber": "Energy Tank",
			"Dynamo (Spider Track)": "Missile Expansion",
			"Hall of the Elders": "Missile Expansion",
			"Antechamber": "Missile Expansion",
			"Warrior Shrine": "Missile Expansion",
			"Magmoor Workstation": "Energy Tank",
			"Ice Ruins East (Spider Track)": "Charge Beam",
			"Chapel of the Elders": "Energy Tank",
			"Ruined Courtyard": "Energy Tank",
			"Quarantine Cave": "Artifact of Truth",
			"Observatory": "Missile Expansion",
			"Research Core": "Missile Expansion",
			"Research Lab Aether (Tank)": "Missile Expansion",
			"Research Lab Aether (Morph Track)": "Missile Expansion",
			"Gravity Chamber (Underwater)": "Missile Expansion",
			"Main Quarry": "X-Ray Visor"
		},
		{
			"Great Tree Chamber": "Missile Expansion",
			"Life Grove Tunnel": "Power Bomb Expansion",
			"Life Grove (Start)": "Missile Expansion",
			"Life Grove (Underwater Spinner)": "Missile Expansion",
			"Furnace (Spider Tracks)": "Missile Expansion",
			"Triclops Pit": "Missile Expansion",
			"Shore Tunnel": "Energy Tank",
			"Fiery Shores (Warrior Shrine Tunnel)": "Energy Tank",
			"Security Access A": "Missile Expansion",
			"Elite Research (Phazon Elite)": "Grapple Beam",
			"Elite Research (Laser)": "Missile Expansion"
		},
		{
			"Root Cave": "Missile Expansion",
			"Main Plaza (Grapple Ledge)": "Energy Tank",
			"Training Chamber": "Missile Expansion",
			"Training Chamber Access": "Phazon Suit",
			"Magma Pool": "Super Missile",
			"Quarantine Monitor": "Power Bomb Expansion",
			"Frost Cave": "Varia Suit",
			"Storage Depot B": "Energy Tank",
			"Elite Control Access": "Plasma Beam",
			"Ventilation Shaft": "Missile Expansion",
			"Phazon Processing Center": "Missile Expansion",
			"Central Dynamo": "Missile Expansion",
			"Metroid Quarantine A": "Missile Expansion"
		},
		{
			"Arbor Chamber": "Power Bomb Expansion",
			"Biohazard Containment": "Missile Expansion",
			"Main Plaza (Tree)": "Missile Expansion",
			"Sunchamber (Ghosts)": "Missile Expansion",
			"Crossway": "Energy Tank",
			"Elder Chamber": "Missile Expansion",
			"Plasma Processing": "Missile Expansion",
			"Phendrana Shorelines (Behind Ice)": "Missile Expansion",
			"Phendrana Shorelines (Spider Track)": "Energy Tank",
			"Chozo Ice Temple": "Missile Expansion",
			"Ice Ruins West": "Missile Expansion",
			"Ice Ruins East (Behind Ice)": "Energy Tank",
			"Research Lab Hydra": "Missile Expansion",
			"Transport Access": "Missile Expansion",
			"Control Tower": "Missile Expansion",
			"Gravity Chamber (Grapple Ledge)": "Missile Expansion",
			"Storage Cave": "Missile Expansion",
			"Security Cave": "Missile Expansion",
			"Storage Depot A": "Wavebuster",
			"Processing Center Access": "Power Bomb",
			"Elite Quarters": "Artifact of Nature",
			"Metroid Quarantine B": "Energy Tank",
			"Fungal Hall B": "Missile Expansion",
			"Phazon Mining Tunnel": "Missile Expansion",
			"Fungal Hall Access": "Missile Expansion"
		}
	]
}

**Comment by etaylor8086** [comment]
> Stuck in Quarry Access room - accessible without wave beam, but cannot be escaped without it.

I apologize, but I'm confused. Both of Quarry Access's doors are purple just to enter the room as well as exit it.

Not to mention, the logic always expects you to to have both Wave and Ice Beam to access Phazon Mines to begin with.

**Comment by KnilKrad** [comment]
Apologies for any confusion, I filed this report on behalf of a friend who actually did the run while I was spectating. He accessed the room from the crashed frigate area, having obtained the ice beam but not the wave beam. According to him, he didn't do any skips to access the room in which the softlock occurred.

**Comment by etaylor8086** [comment]
Did he stream his run at all? Unfortunately I'm not sure if he entered the frigate itself, or some other room, but none of the areas you're describing will softlock you without wave beam. If you can clarify where your friend went, that would be much appreciated!

**Comment by KnilKrad** [comment]
He didn't stream or record it, unfortunately. It was the first time either of us had used the randomizer, and I'm not extremely familiar with the game to begin with. What I know for sure is that after going through the crashed frigate area, he entered the Quarry Access room from the Transport to Tallon Overworld South elevator room, and was able to do so without the wave beam. I suppose it's possible he sequence broke unintentionally at some point or we encountered a bug unrelated to the randomizer, but it didn't seem that way at the time.

**Comment by KnilKrad** [comment]
He definitely didn't go out of bounds at any point. On the off-chance that he did accidently sequence break somewhere, it was definitely at least inbounds.

**Comment by etaylor8086** [comment]
Unfortunately I nor anyone I've mentioned this issue to can reproduce the issue. I'm going to close this for now, but if your friend is able to reproduce and provide more information I will happily re-open this.

Feel free to drop by the randomizer Discord server (https://discord.gg/gymstUz), I'm active on it as well as other randomizer players.
