### ISSUE TITLE
Heat Protection: Varia Only does not seem to work any more

### ISSUE THREAD

**Issue by pkmnfrk** [etaylor8086/metroid-prime-randomizer#25]
Version: 2.0.0
Permalink: OVlDRVo5OTBBMSBWSE4zV1QtNE1HTkpaR09GUFUwTFpaTERRSThDQTRMODlaNEU0MlM1Tkw2Ty0wLTA=

Description of problem:
"Heat Protection: Varia Only" doesn't work. Any suit upgrade is enough to enter heated rooms. For example, I collected the Phazon Suit from "Sunchamber (Ghosts)", and was able to enter Magma Pool without taking damage.

Spoiler log (if available): https://gist.github.com/pkmnfrk/d5ee96ea45b49e9aeb5ab3eabfc3e945

Verify ISO file (if available):  
```
{
	"gameCode": "GM8E01",
	"md5Hash": "d80f1d6d31a97efcf708295a7003ebd2",
	"revision": 2
}
```

**Comment by pkmnfrk** [comment]
(I am aware the hash is not valid, but I have never had issues with anything in the past)

**Comment by etaylor8086** [comment]
Thanks. I'll look into this for the next release.

**Comment by etaylor8086** [comment]
Looks like this is a bug with the patcher with NTSC 1.02 versions of Metroid Prime. Varia-only heat damage *does* still work with 1.00 however.

Filing a bug on the patcher repo, should get fixed soon.
