### ISSUE TITLE
Seed can't be completed (Softlock)

### ISSUE THREAD

**Issue by Zeldameister** [etaylor8086/metroid-prime-randomizer#26]
Version: 2.2.0

Permalink: Qzg4RVFGWDVOSiBFVTlBNkZNLTVSSVBQVUVFWFBVRzlSMzNMT1JDV1lZSjhFVFY4QVlZMkYwVTlFS0cwLTAtMA==

Description of problem:
Got stuck in Phazon Mines, forgot to pick up Spider Ball at Lava Lake. Can't go back anymore, lacking Boost Ball and Thermal Visor + X-ray Visor. I can't go back, I can't move onwoards, what is this shit?!

Spoiler log (if available): 
Lava Lake | "Spider Ball"

Verify ISO file (if available):

**Comment by etaylor8086** [comment]
I'm sorry this happened to you. Unfortunately there are some areas of the game you can get stuck in if you don't have a certain item to escape, but the randomizer does account for as many of these scenarios as possible with the `Point of No Return Items` setting. For instance, it prevents the Boost Ball from being placed in lower Phazon Mines (Ventilation Shaft and beyond), and the Spider Ball from being placed in most of Phazon Mines past Ore Processing; in fact, if the logic expects you to first enter Phazon Mines from Magmoor Caverns, it won't place Spider Ball in Phazon Mines at all.

I do think fleshing out the FAQ to include common softlock points is warranted and something I can get in place for the upcoming 2.2.1 update, but there's only so much I can do on my end to prevent players from softlocking. It's not your fault, it happens to a lot of new players.

For what it's worth, I softlocked myself a few times when I started playing the randomizer. It happens. [We have a pretty active Discord server](http://discord.gg/WWGcay6) if you would also like to get help there.

**Comment by etaylor8086** [comment]
Just to update, I plan on adding Boost Ball and Spider Ball to the beginner friendly preset as well as adding a new Softlocks section to the help documents for the next version.

The preset update won't cut out on every possible softlock (beam rooms for instance) but it should cut down on the number of new players getting stuck in lower Phazon Mines among other spots.
